### PR TITLE
Added Data file

### PR DESCRIPTION
**Pull request by SamiSha99**
Related to #15

### CODE REVIEW

**Review by Amirk390 — CHANGES_REQUESTED** [review]
Removed the different pages from this branch
(statistics, calculator, prices)

**Review by Amirk390 — APPROVED** [review]

**Comment by Karyum** [comment]
@SamiSha99 this pr should contain on 1 file not 3, only the data file

**Comment by Karyum** [comment]
@SamiSha99 what are you doing there was 3 files changed and now there is 5 !!!!!!!!
and i see your commits those are not useful messages that you are adding to the commit

**Comment by Karyum** [comment]
@SamiSha99 what is going on why did you close this ???

**Pull request closed without merging**
